### PR TITLE
Check if type is html

### LINKED ISSUE #870: UFAL/File preview for html is not working
You can see the error here:
https://dspace-dev.ufal.mff.cuni.cz/repository/items/c6a0a8fd-bbea-47a3-9f1d-aee5532355c0
https://dspace-dev.ufal.mff.cuni.cz/repository/items/5cc34d8a-0e94-4bca-a946-95170f21533f

**The reason:** 
The `html` preview is not stored in the DB because it's text value could be too long for storing it in the DB. https://github.com/dataquest-dev/DSpace/blob/dtq-dev/dspace-api/src/main/java/org/dspace/scripts/filepreview/FilePreview.java#L163
And when generating preview on the item view is disabled `create.file-preview.on-item-page-load` there is not way how the html preview could be received.

The solution: Generate the file preview on Item Page load however the `create.file-preview.on-item-page-load` could be `false`.

### PR DESCRIPTION
**Pull request by Paurikova2**
| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem Description
When the preview-generation configuration property is set to false, file previews are not created. However, in the case of large HTML files, the preview content may exceed database limits, preventing it from being saved. Consequently, the preview is never generated or available.

## Proposed Solution
Allow preview generation for HTML files regardless of the preview-generation configuration setting, to ensure the preview is at least created even if it cannot be stored.

## Summary by CodeRabbit

- **New Features**
  - Preview content is now generated for files with the "text/html" format, expanding support for HTML file previews.
- **Bug Fixes**
  - Improved handling of preview availability when previewing is disabled via configuration, ensuring accurate metadata display for HTML bitstreams.

### CODE REVIEW

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/MetadataBitstreamRestRepository.java [hunk 1]
```diff
@@ -107,7 +108,8 @@ public Page<MetadataBitstreamWrapperRest> findByHandle(@Parameter(value = "handl
                 String url = previewContentService.composePreviewURL(context, item, bitstream, contextPath);
                 List<FileInfo> fileInfos = new ArrayList<>();
                 boolean canPreview = previewContentService.canPreview(context, bitstream);
-                if (canPreview) {
+                String mimeType = bitstream.getFormat(context).getMIMEType();
+                if ((mimeType != null && mimeType.startsWith("text/html")) || canPreview) {
```
Comment (milanmajchrak) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/MetadataBitstreamRestRepository.java]: 1. Use also StringUtils.equals - it check that != null condition 
2. Use the `TEXT_HTML_MIME_TYPE` constant
3. Add there comment why we allow generating preview only for html

**Review by milanmajchrak — CHANGES_REQUESTED** [review]

File: dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/MetadataBitstreamRestRepository.java [hunk 2]
```diff
@@ -109,7 +109,9 @@ public Page<MetadataBitstreamWrapperRest> findByHandle(@Parameter(value = "handl
                 List<FileInfo> fileInfos = new ArrayList<>();
                 boolean canPreview = previewContentService.canPreview(context, bitstream);
                 String mimeType = bitstream.getFormat(context).getMIMEType();
-                if ((mimeType != null && mimeType.startsWith("text/html")) || canPreview) {
+                // HTML content could be longer than the limit, so we do not store it in the DB.
+                // It has to be generated even if properties is false.
```
Comment (milanmajchrak) [inline dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/MetadataBitstreamRestRepository.java]: If property `create.file-preview.on-item-page-load` is false. - There is only one property, not properties.

**Review by milanmajchrak — CHANGES_REQUESTED** [review]

**Review by milanmajchrak — APPROVED** [review]

**Review by vidiecan — APPROVED** [review]
