### PR TITLE
UFAL/Matomo fix tracking of the statistics

### LINKED ISSUE #911: UFAL/Matomo issues
The original issue: https://github.com/ufal/clarin-dspace/issues/1177#issuecomment-2768875754
TODO:
- [x] Update the wiki - Secure only to `NO`
- [x] Update download URL - it should be some valid URL with the bitstream name `<DSPACE_UI>/bitstream/handle/<HANDLE>/<BITSTREAM_NAME>`
- [x] Remove the CustomVariable which is deprecated
- [x] Track bitstream download when downloading `allzip` or by cmd

### PR DESCRIPTION
**Pull request by milanmajchrak**
| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Summary by CodeRabbit

- **New Features**
  - Enhanced file download tracking to provide more precise analytics for individual file and ZIP archive downloads.
  - Improved download URL processing ensures clearer differentiation between single downloads and ZIP file downloads.
  
- **Tests**
  - Added comprehensive test coverage to validate the updated download tracking functionality, including scenarios for valid and invalid requests.
  - Introduced a new test class specifically for validating the functionality of the enhanced download tracking.

### CODE REVIEW

File: dspace-api/src/main/java/org/dspace/app/statistics/clarin/ClarinMatomoBitstreamTracker.java [hunk 1]
```diff
@@ -137,8 +154,14 @@ public void trackBitstreamDownload(Context context, HttpServletRequest request,
...
+        if (!isZip) {
+            // Log the user which is downloading the bitstream
+            this.logUserDownloadingBitstream(context, bit);
+        } else {
+            // Track the zip file downloading event
+            this.logUserDownloadingZip(context, item);
+        }
+
         // Track the bitstream downloading event
         trackPage(context, request, item, "Bitstream Download / Single File");
```
Comment (vidiecan) [inline dspace-api/src/main/java/org/dspace/app/statistics/clarin/ClarinMatomoBitstreamTracker.java]: even zip is bitstream download/single file?

**Review by vidiecan — DISMISSED** [review]

File: dspace-api/src/main/java/org/dspace/app/statistics/clarin/ClarinMatomoBitstreamTracker.java (hunk 1 above)
Comment (milanmajchrak) [reply dspace-api/src/main/java/org/dspace/app/statistics/clarin/ClarinMatomoBitstreamTracker.java]: You are right! It should be `Bitstream Download / Zip Archive` thanks.
